package controlefuncionario;

import java.util.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

class ControleFuncionario extends javax.swing.JFrame {        
    private final int NAVEGACAO_NAV = 1;
    private final int NAVEGACAO_NOVO = 2;
    private final int NAVEGACAO_EDITAR = 3;
    private final int NAVEGACAO_EXCLUIR = 4;
    private final int NAVEGACAO_SELECAO = 5;
    
    private int navegacaoDpto;
    private DAO dao;
    
    /**
     * Creates new form ControleFuncionario
     */
    public ControleFuncionario() {
        initComponents();
        setLocationRelativeTo(null); //centralizar o form
        setTitle("Controle de Funcionário");
        
        dao = new DAO();
        
        DefaultTableModel modelo = new DefaultTableModel(new Object[]{"Código", "Nome"}, 0);
        tabDpto.setModel(modelo);
        tabDpto.getColumnModel().getColumn(0).setPreferredWidth(50);
        tabDpto.getColumnModel().getColumn(1).setPreferredWidth(200);        
        ArrayList<Departamento> arrayDpto = dao.getDepartamento();
        for(int i = 0; i < arrayDpto.size(); i++){
            Object linha[] = new Object[] {arrayDpto.get(i).getCodigo(), arrayDpto.get(i).getNome()};
            modelo.addRow(linha);
        }
        
        navegacaoDpto = NAVEGACAO_NAV;
        navegacaoInterfaceDpto();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel10 = new javax.swing.JLabel();
        controleFuncionario = new javax.swing.JTabbedPane();
        departamentos = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabDpto = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textDptoCodigo = new javax.swing.JTextField();
        textDptoNome = new javax.swing.JTextField();
        btnDptoSalvar = new javax.swing.JButton();
        btnDptoCancelar = new javax.swing.JButton();
        btnDptoNovo = new javax.swing.JButton();
        btnDptoEditar = new javax.swing.JButton();
        btnDptoExcluir = new javax.swing.JButton();
        funcionarios = new javax.swing.JPanel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel10.setText("jLabel10");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabDpto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabDpto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabDptoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabDpto);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Departamento"));

        jLabel1.setText("Código:");

        jLabel2.setText("Nome:");

        btnDptoSalvar.setText("Salvar");
        btnDptoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDptoSalvarActionPerformed(evt);
            }
        });

        btnDptoCancelar.setText("Cancelar");
        btnDptoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDptoCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(3, 3, 3)
                        .addComponent(textDptoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textDptoNome)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnDptoSalvar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                                .addComponent(btnDptoCancelar)
                                .addGap(72, 72, 72))))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnDptoCancelar, btnDptoSalvar});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textDptoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textDptoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDptoSalvar)
                    .addComponent(btnDptoCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnDptoNovo.setText("Novo");
        btnDptoNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDptoNovoActionPerformed(evt);
            }
        });

        btnDptoEditar.setText("Editar");
        btnDptoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDptoEditarActionPerformed(evt);
            }
        });

        btnDptoExcluir.setText("Excluir");
        btnDptoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDptoExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout departamentosLayout = new javax.swing.GroupLayout(departamentos);
        departamentos.setLayout(departamentosLayout);
        departamentosLayout.setHorizontalGroup(
            departamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(departamentosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(departamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(departamentosLayout.createSequentialGroup()
                        .addComponent(btnDptoNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDptoEditar)
                        .addGap(94, 94, 94)
                        .addComponent(btnDptoExcluir)))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        departamentosLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnDptoEditar, btnDptoExcluir, btnDptoNovo});

        departamentosLayout.setVerticalGroup(
            departamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(departamentosLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(departamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDptoNovo)
                    .addComponent(btnDptoEditar)
                    .addComponent(btnDptoExcluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        controleFuncionario.addTab("Departamentos", departamentos);

        javax.swing.GroupLayout funcionariosLayout = new javax.swing.GroupLayout(funcionarios);
        funcionarios.setLayout(funcionariosLayout);
        funcionariosLayout.setHorizontalGroup(
            funcionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 414, Short.MAX_VALUE)
        );
        funcionariosLayout.setVerticalGroup(
            funcionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 405, Short.MAX_VALUE)
        );

        controleFuncionario.addTab("Funcionários", funcionarios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(controleFuncionario)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(controleFuncionario)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDptoNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDptoNovoActionPerformed
        navegacaoDpto = NAVEGACAO_NOVO;
        navegacaoInterfaceDpto();
    }//GEN-LAST:event_btnDptoNovoActionPerformed

    private void btnDptoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDptoEditarActionPerformed
        navegacaoDpto = NAVEGACAO_EDITAR;
        navegacaoInterfaceDpto();
    }//GEN-LAST:event_btnDptoEditarActionPerformed

    private void btnDptoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDptoExcluirActionPerformed
        int option = JOptionPane.showConfirmDialog(rootPane, "Confirmar a exclusão?","Sim ou Não", JOptionPane.YES_NO_OPTION); //.showConfirmDialog(rootPane, evt);
        if(option == JOptionPane.YES_OPTION){
            int index = tabDpto.getSelectedRow();
            if (index >= 0 &&  index < tabDpto.getRowCount()){
                int codigoDepartamento = Integer.parseInt(tabDpto.getModel().getValueAt(index, 0).toString());
                boolean excluir = dao.excluirDepartamento(codigoDepartamento);
                if(excluir == true){
                    ((DefaultTableModel)tabDpto.getModel()).removeRow(index);
                } else {
                    JOptionPane.showMessageDialog(rootPane, "ERRO: Exclusão não efetuada.");
                }            
            }
        }
        navegacaoDpto = NAVEGACAO_NAV;
        navegacaoInterfaceDpto();
    }//GEN-LAST:event_btnDptoExcluirActionPerformed

    private void btnDptoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDptoSalvarActionPerformed
        int codigo = Integer.parseInt(textDptoCodigo.getText());
        Departamento departamento = new Departamento(codigo, textDptoNome.getText());        
        if (navegacaoDpto == NAVEGACAO_NOVO) {
            boolean inserir = dao.inserirDepartamento(departamento);
            if(inserir == true){
                DefaultTableModel modelo = (DefaultTableModel) tabDpto.getModel();
                Object linha[] = new Object[] {departamento.getCodigo(), departamento.getNome()};
                modelo.addRow(linha);
            } else {
                JOptionPane.showMessageDialog(rootPane, "ERRO: Inserção não efetuada.");
            }
        } else if (navegacaoDpto == NAVEGACAO_EDITAR) {
            boolean update = dao.atualizarDepartamento(departamento);
            if(update == true){
                int index = tabDpto.getSelectedRow();
                DefaultTableModel modelo = (DefaultTableModel) tabDpto.getModel();
                modelo.setValueAt(departamento.getCodigo(), index, 0);
                modelo.setValueAt(departamento.getNome(), index, 1);            
            } else {
                JOptionPane.showMessageDialog(rootPane, "ERRO: Atualização não efetuada.");                
            }
        }
        navegacaoDpto = NAVEGACAO_NAV;
        navegacaoInterfaceDpto();
    }//GEN-LAST:event_btnDptoSalvarActionPerformed

    private void btnDptoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDptoCancelarActionPerformed
        navegacaoDpto = NAVEGACAO_NAV;
        navegacaoInterfaceDpto();
    }//GEN-LAST:event_btnDptoCancelarActionPerformed

    private void tabDptoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabDptoMouseClicked
        int index = tabDpto.getSelectedRow();
        if (index >= 0 &&  index < tabDpto.getRowCount()){
            int codigoDepartamento = Integer.parseInt(tabDpto.getModel().getValueAt(index, 0).toString());
            Departamento departamento = dao.getDepartamento(codigoDepartamento);
            textDptoCodigo.setText(String.valueOf(departamento.getCodigo()));
            textDptoNome.setText(departamento.getNome());
            navegacaoDpto = NAVEGACAO_SELECAO;
            navegacaoInterfaceDpto();
        }
    }//GEN-LAST:event_tabDptoMouseClicked

        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ControleFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ControleFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ControleFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ControleFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ControleFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDptoCancelar;
    private javax.swing.JButton btnDptoEditar;
    private javax.swing.JButton btnDptoExcluir;
    private javax.swing.JButton btnDptoNovo;
    private javax.swing.JButton btnDptoSalvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTabbedPane controleFuncionario;
    private javax.swing.JPanel departamentos;
    private javax.swing.JPanel funcionarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tabDpto;
    private javax.swing.JTextField textDptoCodigo;
    private javax.swing.JTextField textDptoNome;
    // End of variables declaration//GEN-END:variables

    private void navegacaoInterfaceDpto(){
        switch (navegacaoDpto) {
            case NAVEGACAO_NAV:
                btnDptoNovo.setEnabled(true);
                btnDptoEditar.setEnabled(false);
                btnDptoExcluir.setEnabled(false);
                btnDptoSalvar.setEnabled(false);
                btnDptoCancelar.setEnabled(false);
                setEnabledDepartamento(false);
                cleanDepartamento();
                break;
            case NAVEGACAO_NOVO:
                btnDptoNovo.setEnabled(false);
                btnDptoEditar.setEnabled(false);
                btnDptoExcluir.setEnabled(false);
                btnDptoSalvar.setEnabled(true);
                btnDptoCancelar.setEnabled(true);
                setEnabledDepartamento(true);
                cleanDepartamento();
                break;
            case NAVEGACAO_EDITAR:
                btnDptoNovo.setEnabled(true);
                btnDptoEditar.setEnabled(false);
                btnDptoExcluir.setEnabled(false);
                btnDptoSalvar.setEnabled(true);
                btnDptoCancelar.setEnabled(true);
                setEnabledDepartamento(true);
                textDptoCodigo.setEnabled(false);
                break;
            case NAVEGACAO_EXCLUIR:
                btnDptoNovo.setEnabled(true);
                btnDptoEditar.setEnabled(false);
                btnDptoExcluir.setEnabled(false);
                btnDptoSalvar.setEnabled(false);
                btnDptoCancelar.setEnabled(false);
                setEnabledDepartamento(false);
                cleanDepartamento();
                break;
            case NAVEGACAO_SELECAO:
                btnDptoNovo.setEnabled(true);
                btnDptoEditar.setEnabled(true);
                btnDptoExcluir.setEnabled(true);
                btnDptoSalvar.setEnabled(false);                
                btnDptoCancelar.setEnabled(false);
                setEnabledDepartamento(false);
                break;
            default:
                JOptionPane.showMessageDialog(rootPane, "ERRO: Modo de Navegação Inválido na Interface do Departamento!");
                break;
        }
    }
    

    private void setEnabledDepartamento(boolean enabled){
        textDptoCodigo.setEnabled(enabled);
        textDptoNome.setEnabled(enabled);
    }
    
    private void cleanDepartamento(){
        textDptoCodigo.setText("");
        textDptoNome.setText("");
    }
}
